FROM python:3.10

WORKDIR /app
COPY requirements-fastapi.txt .
COPY src src/

RUN pip install -r requirements-fastapi.txt

EXPOSE 8000

CMD ["uvicorn", "src.api_fastapi:app", "--host", "0.0.0.0", "--port", "8000"]
