stages:
  prepare:
    cmd: python src/data/make_dataset.py data/raw data/preprocessed
    deps:
    - data/raw
    - src/data/make_dataset.py
    outs:
    - data/preprocessed
  train:
    cmd: python src/main.py
    deps:
    - data/preprocessed
    - src/features
    - src/models
    - src/main.py
    outs:
    - models/best_lstm_model.h5
    - models/best_vgg16_model.h5
    - models/concatenate.h5
    - models/tokenizer_config.json
    - models/best_weights.pkl
    - models/mapper.pkl
