global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'category-drift-exporter'
    static_configs:
      - targets: ['prometheus_exporter:9100']
  
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']