name: Test API with Docker Compose

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests

      - name: Start services with Docker Compose
        run: docker-compose up -d --build

      - name: Wait for BentoML to be ready
        run: |
          echo "Waiting for BentoML..."
          for i in {1..20}; do
            curl -s http://localhost:3000/healthz && break
            echo "Still waiting..."
            sleep 5
          done

      - name: Run API tests with pytest
        run: pytest tests/

      - name: Stop Docker services
        if: always()
        run: docker-compose down
