name: Build and Push Docker Images

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push images
        run: |
          # Build images
          docker compose build

          # Tag images
          docker tag mlops_classification_e-commerce-bentoml:latest ghcr.io/${{ github.repository }}/bentoml:latest
          docker tag mlops_classification_e-commerce-fastapi:latest ghcr.io/${{ github.repository }}/fastapi:latest
          docker tag mlops_classification_e-commerce-streamlit:latest ghcr.io/${{ github.repository }}/streamlit:latest
          docker tag mlops_classification_e-commerce-prometheus-exporter:latest ghcr.io/${{ github.repository }}/prometheus-exporter:latest

          # Push images
          docker push ghcr.io/${{ github.repository }}/bentoml:latest
          docker push ghcr.io/${{ github.repository }}/fastapi:latest
          docker push ghcr.io/${{ github.repository }}/streamlit:latest
          docker push ghcr.io/${{ github.repository }}/prometheus-exporter:latest
