name: Build and Push Docker Images

on:
  push:
    branches: [master]
    paths:
      - 'src/**'
      - 'Dockerfile.*'
      - 'docker-compose.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push FastAPI
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.fastapi
          push: true
          tags: ghcr.io/${{ github.repository }}/fastapi:latest

      - name: Build and push Streamlit
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.streamlit
          push: true
          tags: ghcr.io/${{ github.repository }}/streamlit:latest

      - name: Build and push Prometheus Exporter
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.prometheus-exporter
          push: true
          tags: ghcr.io/${{ github.repository }}/prometheus-exporter:latest
